on: 
  push: 
    # tags:

jobs:
  default-color:
    runs-on: ubuntu-20.04
    steps:
      - run: git clone https://gitlab.com/tista500/plata-theme.git .
      - run: >-
          sudo apt install
          libgtk-3-dev
          autoconf 
          automake
          inkscape
          libgdk-pixbuf2.0-dev
          libglib2.0-dev
          libxml2-utils
          pkg-config
          sassc
          libmarco-dev
          zip
      - run: ./autogen.sh --prefix="$(pwd)/build" --enable-gtk_next --enable-plank
      - run: make
      - run: make install