name: Build Themes
on: 
  push:
    tags:
      - '**'

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Save asset upload upload
        run: echo "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt
      - name: Upload upload_url file
        uses: actions/upload-artifact@v1
        with:
          name: upload_url
          path: upload_url.txt
  build-color:
    runs-on: ubuntu-20.04
    needs: create-release
    strategy:
      matrix:
        color: [
          '{"name":"Indigo-default","selection_color":"#3F51B5","accent_color":"#7986CB","suggestion_color":"#673AB7"}',
          '{"name":"Red","selection_color":"#F44336","accent_color":"#E57373","suggestion_color":"#FF5722"}',
          '{"name":"Pink","selection_color":"#E91E63","accent_color":"#F06292","suggestion_color":"#F44336"}',
          '{"name":"Purple","selection_color":"#9C27B0","accent_color":"#BA68C8","suggestion_color":"#E91E63"}',
          '{"name":"Deep-Purple","selection_color":"#673AB7","accent_color":"#9575CD","suggestion_color":"#9C27B0"}',
          '{"name":"Blue","selection_color":"#2196F3","accent_color":"#64B5F6","suggestion_color":"#3F51B5"}',
          '{"name":"Light-Blue","selection_color":"#03A9F4","accent_color":"#4FC3F7","suggestion_color":"#2196F3"}',
          '{"name":"Cyan","selection_color":"#00BCD4","accent_color":"#4DD0E1","suggestion_color":"#03A9F4"}',
          '{"name":"Teal","selection_color":"#009688","accent_color":"#4DB6AC","suggestion_color":"#00BCD4"}',
          '{"name":"Green","selection_color":"#4CAF50","accent_color":"#81C784","suggestion_color":"#009688"}',
          '{"name":"Light-Green","selection_color":"#8BC34A","accent_color":"#AED581","suggestion_color":"#4CAF50"}',
          '{"name":"Lime","selection_color":"#CDDC39","accent_color":"#DCE775","suggestion_color":"#8BC34A"}',
          '{"name":"Yellow","selection_color":"#FFEB3B","accent_color":"#FFF176","suggestion_color":"#CDDC39"}',
          '{"name":"Amber","selection_color":"#FFC107","accent_color":"#FFD54F","suggestion_color":"#FFEB3B"}',
          '{"name":"Orange","selection_color":"#FF9800","accent_color":"#FFB74D","suggestion_color":"#FFC107"}',
          '{"name":"Deep-Orange","selection_color":"#FF5722","accent_color":"#FF8A65","suggestion_color":"#FF9800"}'
        ]
    steps:
      - run: git clone https://gitlab.com/tista500/plata-theme.git .
      - name: Prepare system
        run: >
          sudo apt install
          libgtk-3-dev
          autoconf 
          automake
          inkscape
          libgdk-pixbuf2.0-dev
          libglib2.0-dev
          libxml2-utils
          pkg-config
          sassc
          libmarco-dev
          zip
          jq
      - name: Prepare environment
        run: >
          ./autogen.sh --prefix="$(pwd)/build" --enable-gtk_next --enable-plank --enable-telegram --enable-tweetdeck --enable-airforsteam 
          --with-selection_color=$(jq -r '.selection_color' <<< '${{ matrix.color }}') 
          --with-accent_color=$(jq -r '.accent_color' <<< '${{ matrix.color }}') 
          --with-suggestion_color=$(jq -r '.suggestion_color' <<< '${{ matrix.color }}')
      - name: Build images and assets
        run: make
      - name: Build theme
        run: make install
      - name: Pack theme
        uses: thedoctor0/zip-release@0.4.1
        with:
          path: .
          directory: build/share/themes
          filename: release.zip
      - name: Download upload_url file
        uses: actions/download-artifact@v2
        with:
          name: upload_url
      - name: Read upload_url file
        id: upload_url
        run: |
          echo "::set-output name=url::$(cat upload_url.txt)"
          echo "::set-output name=name::$(jq -r '.name' <<< '${{ matrix.color }}')"
      - name: Upload Theme to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload_url.outputs.url }}
          asset_path: build/share/themes/release.zip
          asset_name: ${{ steps.upload_url.outputs.name }}.zip
          asset_content_type: application/zip
