name: Check for new releases
on: 
  schedule:
    - cron:  '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest theme release
        id: theme-version
        run: |
          version=$(curl -sS https://gitlab.com/api/v4/projects/8656645/releases?per_page=1 | jq -r '.[].tag_name')
          echo "Theme Release version: $version"
          echo "::set-output name=version::$version"
      - name: Get latest repository release
        id: repo-version
        run: |
          version=$(curl -sS https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest| jq -r '.tag_name')
          echo "Own repository release version: $version"
          echo "::set-output name=version::$version"
      - name: Checkout repository
        uses: actions/checkout@v1
        if: ${{ steps.theme-version.outputs.version != steps.repo-version.outputs.version }}
      - name: Bump version and push tag
        if: ${{ steps.theme-version.outputs.version != steps.repo-version.outputs.version }}
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.theme-version.outputs.version }}
